apiVersion: v1
kind: Namespace
metadata:
  name: demo  # Create the 'demo' namespace

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: demo  # Set the namespace to 'demo'
spec:
  replicas: 3  # Setting the number of replicas to 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html-volume
      volumes:
      - name: html-volume
        configMap:
          name: nginx-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: demo  # Set the namespace to 'demo'
data:
  index.html: |
    <html>
      <head><title>Welcome</title></head>
      <body>
        <h1>Welcome to Kubernetes Event</h1>
      </body>
    </html>

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: demo  # Set the namespace to 'demo'
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 80
  type: LoadBalancer  # Change to LoadBalancer if using a cloud provider that supports external access
